---
title: "1. Deck The Halls"
body-classes: lyrics has-chords
---

## Intro

<div class="abc-wrap"><div class="abc" data-abc="M:4/4&#10;L:1/4&#10;K:D&#10;&quot;D&quot;A&gt;G F E | &quot;G&quot;D E &quot;D&quot;F D | &quot;Em&quot;E/F/G/E/ &quot;D&quot;F&gt;E | &quot;A7&quot;D C &quot;D&quot;D2 ||"></div></div>

## Verse 1

::: {.cline}
<span class="ln"><span class="cw"><span class="ch">D</span>Deck the halls with </span><span class="cw"><span class="ch">Bm</span>boughs of holly</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">A7</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">D</span>’Tis the season </span><span class="cw"><span class="ch">Bm</span>to be jolly</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">A7</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">A7</span>Don we now our </span><span class="cw"><span class="ch">D</span>gay apparel</span></span>
<span class="ln"><span class="cw"><span class="ch">D</span>Fa-la-la, </span><span class="cw"><span class="ch">Bm</span>la-la-la, </span><span class="cw"><span class="ch">A</span>la, </span><span class="cw"><span class="ch">E7</span>la, </span><span class="cw"><span class="ch">A</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">D</span>Troll the ancient </span><span class="cw"><span class="ch">Bm</span>Yule-tide carol</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">G</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A7</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la</span></span>
:::

## Interlude

<div class="abc-wrap"><div class="abc" data-abc="M:4/4&#10;L:1/4&#10;K:D&#10;&quot;D&quot;A&gt;G F E | &quot;G&quot;D E &quot;D&quot;F D | &quot;Em&quot;E/F/G/E/ &quot;D&quot;F&gt;E | &quot;A7&quot;D C &quot;D&quot;D2 ||"></div></div>

## Verse 2

::: {.cline}
<span class="ln"><span class="cw"><span class="ch">D</span>See the blazing </span><span class="cw"><span class="ch">Bm</span>Yule before us</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">A7</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">D</span>Strike the harp and </span><span class="cw"><span class="ch">Bm</span>join the chorus</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">A7</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">A7</span>Follow me in </span><span class="cw"><span class="ch">D</span>merry measure</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">D</span>Fa-la-la-</span><span class="cw"><span class="ch">Bm</span>la-la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A</span>la, </span></span><span class="cw"><span class="ch">E7</span>la, </span><span class="cw"><span class="ch">A</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">D</span>While I tell of </span><span class="cw"><span class="ch">Bm</span>Yuletide treasure</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">G</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A7</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la</span></span>
:::

## Interlude

<div class="abc-wrap"><div class="abc" data-abc="M:4/4&#10;L:1/4&#10;K:D&#10;&quot;D&quot;A&gt;G F E | &quot;G&quot;D E &quot;D&quot;F D | &quot;Em&quot;E/F/G/E/ &quot;D&quot;F&gt;E | &quot;A7&quot;D C &quot;D&quot;D2 ||"></div></div>

## Verse 3

::: {.cline}
<span class="ln"><span class="cw"><span class="ch">D</span>Fast away the </span><span class="cw"><span class="ch">Bm</span>old year passes -</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">A7</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">D</span>Hail the new, ye </span><span class="cw"><span class="ch">Bm</span>lads and lasses</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">A7</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">A7</span>Sing we joyous </span><span class="cw"><span class="ch">D</span>all together</span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">D</span>Fa-la-la-</span><span class="cw"><span class="ch">Bm</span>la-la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A</span>la, </span></span><span class="cw"><span class="ch">E7</span>la, </span><span class="cw"><span class="ch">A</span>la</span></span>
<span class="ln"><span class="cw"><span class="ch">D</span>Heedless of the </span><span class="cw"><span class="ch">Bm</span>wind and weather –</span></span>
<span class="ln"><span class="nb"><span class="cw">(</span><span class="cw"><span class="ch">G</span>Fa-la-la-la-</span><span class="cw"><span class="ch">D</span>la, </span></span><span class="nb"><span class="cw">la-</span><span class="cw"><span class="ch">A7</span>la, </span></span><span class="cw">la, </span><span class="cw"><span class="ch">D</span>la - *3 times*)</span></span>
:::

::: {.songnav}
[&larr; Programme](../index.qmd){.nav-prev}
[Winter Wonderland &rarr;](winter-wonderland.qmd){.nav-next}
:::
