---
title: "4. Frosty the Snowman"
body-classes: lyrics
---

## Verse 1

Frosty the Snowman  
Was a jolly happy soul,  
With a corn cob pipe and a button nose  
And two eyes made out of coal  

Frosty the Snowman  
Is a fairy tale they say,  
He was made of snow but the children know  
How he came to life one day  

## Chorus

*There must have been some magic*  
*In that old silk hat they found,*  
*For when they placed it on his head*  
*He began to dance around\!*  

## Verse 2

Oh, Frosty the Snowman  
Was alive as he could be,  
And the children say  
He could laugh and play  
Just the same as you and me  

Frosty the Snowman  
Knew the sun was hot that day,  
So he said “Let’s run and we’ll have some fun,  
Now before I melt away.”  
Down to the village  
With a broomstick in his hand,  
Running here and there  
All around the square,  
Saying, “Catch me if you can\!”  

## Chorus

*He led them down the streets of town*  
*Right to the traffic cop,*  
*And he only paused a moment when*  
*He heard him holler “STOP\!”*  

## Verse 3

For Frosty the Snowman  
Had to hurry on his way,  
But he waved goodbye,  
Saying “Don’t you cry \-  
I’ll be back again someday\!”  

## Chorus

*Thumpity \- thump \- thump*  
*Thumpity \- thump \- thump*  
*Look at Frosty go\!*  

## Chorus

*Thumpity \- thump \- thump*  
*Thumpity \- thump \- thump*  
*Over the hills of snow*  

## Chorus

*Thumpity \- thump \- thump*  
*Thumpity \- thump \- thump*  
*Look at Frosty go\!*  

::: {.songnav}
[&larr; Santa Claus is Coming to Town](santa-claus-is-coming-to-town.qmd){.nav-prev}
[O Hanukkah &rarr;](o-hanukkah.qmd){.nav-next}
:::
