---
title: "2. Viva la Vida"
body-classes: lyrics has-chords
---

## Intro

::: {.cline}
<span class="ln"><span class="ibar"><span class="ch">Db</span><span class="ch">Ebadd11</span><span class="ch">Ab</span><span class="ch">Fm</span><span class="ch">x2</span></span></span>
:::

## Verse 1

::: {.cline}
<span class="ln"><span class="cw">I used to </span><span class="cw"><span class="ch">Db</span>rule the </span><span class="cw"><span class="ch">Ebadd11</span>world</span></span>
<span class="ln"><span class="cw">Seas would </span><span class="cw"><span class="ch">Ab</span>rise when I gave the </span><span class="cw"><span class="ch">Fm</span>word</span></span>
<span class="ln"><span class="cw">Now in the morning I </span><span class="nb"><span class="cw"><span class="ch">Db</span>sleep a</span><span class="cw"><span class="ch">Ebadd11</span>lone</span></span></span>
<span class="ln"><span class="cw">Sweep the </span><span class="cw"><span class="ch">Ab</span>streets I used to </span><span class="cw"><span class="ch">Fm</span>own</span></span>
:::

## Interlude

::: {.cline}
<span class="ln"><span class="ibar"><span class="ch">Db</span><span class="ch">Ebadd11</span><span class="ch">Ab</span><span class="ch">Fm</span><span class="ch">x2</span></span></span>
:::

## Verse 2

::: {.cline}
<span class="ln"><span class="cw">I used to </span><span class="cw"><span class="ch">Db</span>roll the </span><span class="cw"><span class="ch">Ebadd11</span>dice</span></span>
<span class="ln"><span class="cw">Feel the </span><span class="cw"><span class="ch">Ab</span>fear in my enemy&#x27;s </span><span class="cw"><span class="ch">Fm</span>eyes</span></span>
<span class="ln"><span class="cw">Listen as the </span><span class="cw"><span class="ch">Db</span>crowd would </span><span class="cw"><span class="ch">Ebadd11</span>sing:</span></span>
<span class="ln"><span class="cw">&quot;Now the </span><span class="cw"><span class="ch">Ab</span>old king is dead! Long </span><span class="cw"><span class="ch">Fm</span>live the king!&quot;</span></span>
<span class="ln"><span class="cw">One minute I </span><span class="cw"><span class="ch">Db</span>held the </span><span class="cw"><span class="ch">Ebadd11</span>key</span></span>
<span class="ln"><span class="cw">Next the </span><span class="cw"><span class="ch">Ab</span>walls were closed on </span><span class="cw"><span class="ch">Fm</span>me</span></span>
<span class="ln"><span class="cw">And I discovered that my </span><span class="cw"><span class="ch">Db</span>castles </span><span class="cw"><span class="ch">Ebadd11</span>stand</span></span>
<span class="ln"><span class="cw">Upon </span><span class="nb"><span class="cw"><span class="ch">Ab</span>pillars of salt and pill</span><span class="cw"><span class="ch">Fm</span>ars </span></span><span class="cw">of sand</span></span>
:::

## Chorus

::: {.cline}
<span class="ln"><span class="cw">I </span><span class="cw"><span class="ch">Db</span>hear Jerusalem </span><span class="cw"><span class="ch">Ebadd11</span>bells are ringing</span></span>
<span class="ln"><span class="cw"><span class="ch">Ab</span>Roman Cavalry </span><span class="cw"><span class="ch">Fm</span>choirs are singing</span></span>
<span class="ln"><span class="cw"><span class="ch">Db</span>Be my mirror, my </span><span class="cw"><span class="ch">Ebadd11</span>sword and shield</span></span>
<span class="ln"><span class="cw">My </span><span class="cw"><span class="ch">Ab</span>missionaries in a </span><span class="cw"><span class="ch">Fm</span>foreign field</span></span>
<span class="ln"><span class="cw"><span class="ch">Db</span>For some reason I </span><span class="cw"><span class="ch">Ebadd11</span>can&#x27;t explain</span></span>
<span class="ln"><span class="cw"><span class="ch">Ab</span>Once you&#x27;d gone there was </span><span class="cw"><span class="ch">Fm</span>never</span></span>
<span class="ln"><span class="cw">Never an </span><span class="cw"><span class="ch">Db</span>honest </span><span class="cw"><span class="ch">Ebadd11</span>word</span></span>
<span class="ln"><span class="cw">And that was </span><span class="cw"><span class="ch">Cm</span>when I ruled the </span><span class="cw"><span class="ch">Fm</span>world</span></span>
:::

## Interlude

::: {.cline}
<span class="ln"><span class="ibar"><span class="ch">Db</span><span class="ch">Ebadd11</span><span class="ch">Ab</span><span class="ch">Fm</span><span class="ch">x2</span></span></span>
:::

## Verse 3

::: {.cline}
<span class="ln"><span class="cw">It was the wicked and </span><span class="cw"><span class="ch">Db</span>wild </span><span class="cw"><span class="ch">Ebadd11</span>wind</span></span>
<span class="ln"><span class="cw">Blew down the </span><span class="cw"><span class="ch">Ab</span>doors to let me </span><span class="cw"><span class="ch">Fm</span>in</span></span>
<span class="ln"><span class="cw">Shattered windows and the </span><span class="cw"><span class="ch">Db</span>sound of </span><span class="cw"><span class="ch">Ebadd11</span>drums</span></span>
<span class="ln"><span class="cw">People </span><span class="cw"><span class="ch">Ab</span>couldn&#x27;t believe what </span><span class="cw"><span class="ch">Fm</span>I&#x27;d become</span></span>
<span class="ln"><span class="nb"><span class="cw">Revolutio</span><span class="cw"><span class="ch">Db</span>naries </span></span><span class="cw"><span class="ch">Ebadd11</span>wait</span></span>
<span class="ln"><span class="cw">For my </span><span class="cw"><span class="ch">Ab</span>head on a silver </span><span class="cw"><span class="ch">Fm</span>plate</span></span>
<span class="ln"><span class="cw">Just a puppet on a </span><span class="cw"><span class="ch">Db</span>lonely </span><span class="cw"><span class="ch">Ebadd11</span>string</span></span>
<span class="ln"><span class="cw">Oh, </span><span class="cw"><span class="ch">Ab</span>who would ever want to be </span><span class="cw"><span class="ch">Fm</span>king?</span></span>
:::

## Chorus

::: {.cline}
<span class="ln"><span class="cw">I </span><span class="cw"><span class="ch">Db</span>hear Jerusalem </span><span class="cw"><span class="ch">Ebadd11</span>bells are ringing</span></span>
<span class="ln"><span class="cw"><span class="ch">Ab</span>Roman Cavalry </span><span class="cw"><span class="ch">Fm</span>choirs are singing</span></span>
<span class="ln"><span class="cw"><span class="ch">Db</span>Be my mirror, my </span><span class="cw"><span class="ch">Ebadd11</span>sword and shield</span></span>
<span class="ln"><span class="cw">My </span><span class="cw"><span class="ch">Ab</span>missionaries in a </span><span class="cw"><span class="ch">Fm</span>foreign field</span></span>
<span class="ln"><span class="cw"><span class="ch">Db</span>For some reason I </span><span class="cw"><span class="ch">Ebadd11</span>can&#x27;t explain</span></span>
<span class="ln"><span class="cw">I </span><span class="cw"><span class="ch">Ab</span>know Saint Peter won&#x27;t </span><span class="cw"><span class="ch">Fm</span>call my name</span></span>
<span class="ln"><span class="cw">Never an </span><span class="cw"><span class="ch">Db</span>honest </span><span class="cw"><span class="ch">Ebadd11</span>word</span></span>
<span class="ln"><span class="cw">But that was </span><span class="cw"><span class="ch">Cm</span>when I ruled the </span><span class="cw"><span class="ch">Fm</span>world</span></span>
:::

## Interlude

::: {.cline}
<span class="ln"><span class="ibar"><span class="ch">Db</span><span class="ch">Fm</span><span class="ch">x3</span></span></span>
<span class="ln"><span class="ibar"><span class="ch">Ebadd11</span><span class="ch">Ebadd11</span></span></span>
<span class="ln"><span class="nb"><span class="cw">Oh</span><span class="cw"><span class="ch">Db</span>hhhh</span><span class="cw"><span class="ch">Ebadd11</span>h </span></span><span class="nb"><span class="cw">Oh</span><span class="cw"><span class="ch">Ab</span>hhhh</span><span class="cw"><span class="ch">Fm</span>h</span></span></span>
<span class="ln"><span class="nb"><span class="cw">Oh</span><span class="cw"><span class="ch">Db</span>hhhh</span><span class="cw"><span class="ch">Ebadd11</span>h </span></span><span class="nb"><span class="cw">Oh</span><span class="cw"><span class="ch">Ab</span>hhhh</span><span class="cw"><span class="ch">Fm</span>h</span></span></span>
:::

## Chorus

::: {.cline}
<span class="ln"><span class="cw">I </span><span class="cw"><span class="ch">Db</span>hear Jerusalem </span><span class="cw"><span class="ch">Ebadd11</span>bells are ringing</span></span>
<span class="ln"><span class="cw"><span class="ch">Ab</span>Roman Cavalry </span><span class="cw"><span class="ch">Fm</span>choirs are singing</span></span>
<span class="ln"><span class="cw"><span class="ch">Db</span>Be my mirror, my </span><span class="cw"><span class="ch">Ebadd11</span>sword and shield</span></span>
<span class="ln"><span class="cw">My </span><span class="cw"><span class="ch">Ab</span>missionaries in a </span><span class="cw"><span class="ch">Fm</span>foreign field</span></span>
<span class="ln"><span class="cw"><span class="ch">Db</span>For some reason I </span><span class="cw"><span class="ch">Ebadd11</span>can&#x27;t explain</span></span>
<span class="ln"><span class="cw">I </span><span class="cw"><span class="ch">Ab</span>know Saint Peter won&#x27;t </span><span class="cw"><span class="ch">Fm</span>call my name</span></span>
<span class="ln"><span class="cw">Never an </span><span class="cw"><span class="ch">Db</span>honest </span><span class="cw"><span class="ch">Ebadd11</span>word</span></span>
<span class="ln"><span class="cw">But that was </span><span class="cw"><span class="ch">Cm</span>when I ruled the </span><span class="cw"><span class="ch">Fm</span>world</span></span>
:::

## Outro

::: {.cline}
<span class="ln"><span class="nb"><span class="cw"><span class="ch">Db</span>Oooo</span><span class="cw"><span class="ch">Ebadd11</span>oh </span></span><span class="nb"><span class="cw"><span class="ch">Cm</span>Ooooo</span><span class="cw"><span class="ch">Fm</span>oh</span></span></span>
<span class="ln"><span class="nb"><span class="cw"><span class="ch">Db</span>Oooo</span><span class="cw"><span class="ch">Ebadd11</span>oh </span></span><span class="nb"><span class="cw"><span class="ch">Cm</span>Ooooo</span><span class="cw"><span class="ch">Fm</span>oh</span></span></span>
:::

::: {.songnav}
[&larr; End of Beginning](end-of-beginning.qmd){.nav-prev}
[Programme &rarr;](../index.qmd){.nav-next}
:::
